### ISSUE TITLE
Překlad stránek do EN

### ISSUE THREAD

**Issue by shanataru** [vojtatom/vddt#10]
TODO's tohoto issue:

- [x] přeložit flash messages
- [x] přeložit app/forms a sepsat co všechno se rozbilo
- [x] přeložit app/model a sepsat co všechno se rozbilo
- [x] přeložit app/tables a sepsat co všechno se rozbilo

Podrobnosti ve vláknu níže.

---

Update - mohou se přeložit app forms, alespoň uvidíme co všechno se rozbije (nemuselo by toho být tolik)

**Comment by vojtatom** [comment]
Většina věcí přeložena, zbývá to co je v záhlaví issue.

**Comment by vojtatom** [comment]
Prosím někdo pak zkontrolujte velká malá písmena a konzistenci názvů mezi talčítkami a popiskami materiálu, binárky a masky - binárky mají modify, zbytek edit, někde jsou velká písmena
