### ISSUE TITLE
Nelze nahrát masku

### ISSUE THREAD

**Issue by shanataru** [vojtatom/vddt#14]
Sloupec **universal** v tabulce **mask** je typu int(11)

---

Doctrine\DBAL\Exception\DriverException

An exception occurred while executing 'INSERT INTO mask (date, universal, preview_id, path, public, user_id, note, name, fileSize, format, height, width) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "universal", 6, "\/data\/mask\/55a019c92799025.41470204.jpg", 0, 5, "mask test, random jpg", "mask001", 91388, "jpg", 390, 600]:

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'universal' for column 'universal' at row 1

**Comment by vojtatom** [comment]
Maska se nahrává ale něco je pořád špatně...

**Comment by vojtatom** [comment]
Opraveno v 59061113820bde32d1b7018eb8d0efa6d7b57534
