### ISSUE TITLE
Formulář vyhledávání

### ISSUE THREAD

**Issue by vojtatom** [vojtatom/vddt#16]
Je potřeba vytvořit rozšířený formulář, který může být prozatím na samostatné stránce.
 * omezení vyhledávání věcí v časovém intervalu (vytvořeno před 21.11.2017)
 * omezení vyhledávání na věci o určitých rozměrech (užší/širší než 800px)
 * omezení vyhledávání na věci určitého typu (binárky/materiál/zpracování/maska)
 * požadavky specifické na typ výsledku (pouze univerzální/přiřazené masky)

**Comment by AnnaMoudra** [comment]
Ještě chybí inNote vyhledávání a nějaké vetší testování funkcionality.
Řazení podle relevance je zatím nefunkční.

**Comment by AnnaMoudra** [comment]
inNote pro binárky a masky funguje, v soucasnosti na substringy (tedy najde vic nez vyhledavani na cela slova)

**Comment by vojtatom** [comment]
Prosím může někdo ověřit, jestli je toto pořád aktivní issue? Vím, že jsem to opravoval, ale (asi) jsem to v tu chvíli tu zapomněl zavřít a nevím, jestli nebylo ještě něco potřeba.

**Comment by vojtatom** [comment]
edit - ten poslední comment nepatří sem, ale k issue #18
