### ISSUE TITLE
Eliminace <table>

### ISSUE THREAD

**Issue by vojtatom** [vojtatom/vddt#20]
Přepsání templatů detail.latte u všech entit tak, aby se na nich eliminoval element `<table>`, nejspíše by bylo dobré ho nahradit pomocí `<dl>`. Bude se pak lépe formátovat.

**Comment by shanataru** [comment]
Ty <dl> jsem dala pod <div class="info"> takze uz maji nejaky styl

**Comment by vojtatom** [comment]
Je potřeba dodělat styly, už se na tom dělá - pull reaquest cards #23 bude obsahovat upgrade cssek a tenhle issue se bude řešit.

**Comment by vojtatom** [comment]
9a6888fbb328c617007624cf2b255e285265f843 dodány nové styly, vyřešeno 🎉
