### ISSUE TITLE
Ikonky

### ISSUE THREAD

**Issue by vojtatom** [vojtatom/vddt#27]
Kdyby byl někdo tak hodný a chtělo se mu chvíli neprogramovat, tak potřebujeme sadu ikonek:

- [x] Logo
- [x]  Homepage
- [x]  Profile
- [x] Settings
- [x] Sign in
- [x] Sign out
- [x] Search
- [x] Advanced search

Pár jich máme, tak třeba doplnit sadu a nebo udělat nové - jak se vám to bude hodit. Barevné schéma a nějaké nápady jsou na slacku. Všechny z nich skončí v záhlaví stránky. 🐼

**Comment by shanataru** [comment]
yellow: #fbc050
beige: #ffedcb
green: #b2ddc6
blue: #347191
red: #913434
pink: #ddb2b2
gray:#b9b9b9

**Comment by shanataru** [comment]
V master větvi jsou už  dané nějaké ikony

**Comment by shanataru** [comment]
Ještě chybí zobrazení ikonky search a log in

**Comment by vojtatom** [comment]
Ikonky vyřešeny 🎈
