### ISSUE TITLE
Příležitostné testování

### ISSUE THREAD

**Issue by shanataru** [vojtatom/vddt#29]
Testuje se na http://vddt.miladamoudra.com

- [x] **1. Vyhledávání zadáním keywords** - bez zaškrtávání typu souboru (materiál, maska, ...)
Pokud žádný soubor nebyl nalezen, správně se zobrazí no data, ale pokud by to mělo něco najít, správně zobrazí výsledky masek a binárek **ale pokud má ve výsledcích být i (nebo jenom) materiály**, vyhodí výjímku:
```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #14 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'vddt.t1_.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```
Podobně nefunguje ani když se zaškrtne pole 'Material'.
Zaškrtnutí 'Material' bez keywords funguje.

- [x] **2. Pole 'Maximum width' a 'Minimum height'**
Po vyplnění pole se zobrazí nevalidní výsledky, které jsou způsobeny pravděpodobně zaměněním těchto 2 polí?

- [x]  **3. Napsání neplatné ID masky/materiálu do URL**
Aplikace spadne - trying to get property of non-object

- [x]  **4. Napsání ID privátní masky/materiálu do URL**
Aplikace normálně zobrazí detail privátní masky/materiálu jiného uživatele.

 - [x] **5. Odmazání value pro search**
Detailní info viz níže.

---
Testování: 3. 12. 2017

- [x]  **6. Detail masky**
Odkazy 'link to a texture' a 'download' nefungují.

- [x]  **7. Neexistující e-mail**
Pokus o přihlášení se na neexistující e-mail vyhodí výjimku:
![active](https://user-images.githubusercontent.com/28073079/33526758-fee9356c-d845-11e7-90d6-0232b902176f.png)

- [x]  **8. Nelze seřadit zlinkované věci podle autorů**
U detailu materiálu/masky nelze seřadit zlinkované masky/materiály podle autorů.
![bug8](https://user-images.githubusercontent.com/28073079/33526858-39f9db10-d847-11e7-8b8d-910a7cc541e1.png)

**Comment by shanataru** [comment]
Ještě mimo ten form:
Když není člověk přihlášený a klikne na search vedle toho pole nahoře na stránce tak to spadne.

**Comment by shanataru** [comment]
Ten první bug už asi nadobro zmizel?

**Comment by AnnaMoudra** [comment]
První bug se mi nepovedlo nasimulovat. Opravila jsem bug s prohozenými poli u dimenzí.

**Comment by wellborntea** [comment]
Při odmazání value pro search, material, binary, mask nebo processing z URL při vyhledávání stránka nespadne, pouze vyhodí error notice
(např. http://vddt.miladamoudra.com/search/results?values%5Bsearch%5D=test&values%5Bmaterial&values%5Bmask%5D=0&values%5Bbinary%5D=0&values%5Bprocessing%5D=0&values%5Buniversal%5D=0&values%5Bformats%5D=&values%5Btake%5D=&values%5Bmove%5D=&values%5Blanguage%5D=     - odmazáno "%5D=0" za slovem "material")

**Comment by vojtatom** [comment]
Ad bezpečnost a přístupy - místo checkPrivileges() které akorát házelo výjimky, takže apliakce padala má teď každý prezenter v sobě 3 funkce pro 3 stupně ověření přístupu:

1. checkAccessGeneral() ověřuje pouze pokud záznam existuje a není soukromý
2. checkAccessUser() ověřuje zda-li je záznam veřejný a uživatel je přihlášený
3. checkAccessOwner() ověřuje vše výše plus zda-li je uživatel vlastníkem

V opačném případě neshody je vyhozena hláška a uživatel je přesměřován. Konkrétní implementace je v BasePresenter.php, jednotlivých modelech, které poskytují entity a ověření pak v Model.php.

**Comment by vojtatom** [comment]
Tady to issue je zařazené do milestone vyhledávání, jelikož je všechno (prozatím) vyřízeno. Případné nové bugy prosím dávejte do nového issue, které bude mimo tento milestone.
