### ISSUE TITLE
Vyhledávání - diskuse

### ISSUE THREAD

**Issue by vojtatom** [vojtatom/vddt#3]
TODO tohoto vlákna:

- [x] návrh metod QueryBuilderů
- [x] napsání custom gridů
- [x] vyřešení issue namespaců - jak se kde co jinak jmenuje (mask_id, id_mask, id atp...)
- [x] implementace QueryBuilderů
- [x] funguje?

Podrobnosti ohledně úkolů viz níže.

---

V commitu a6a11578cbd66e73f95fdb2bdb40c7236b055c5b přibyl nějaký základ pro vyhledávání. 

V základě budeme mít 2 módy na vyhledávání, tak že dostaneme od uživatele čistě text a podle něj něco najdeme. Druhý způsob bude, že udělám nějaký formulář, pomocí kterého on si nakliká co hledá (nějaké rozsahy, něco takového...) a dostane výsledek.

## Jak vyhledat
> Toto je návrh:
>
> Tudíž potřebujeme se umět poprat s nějakým simple vyhledáváním a pak vymyslet nějaký syntax pro zapsání něčeho složitějšího (ala google search v mailu mě napadá) - jedak bude moci uživatel to tam zadat do textového pole podle jeho představ a jednak budeme moci přetransformovat výstup z toho formuláře do té syntaxe a předhodit to našemu vyhledávači - což znamená, že stačí když bude umět jen tady ten kill'em all formát, protože do něj půjde převést cokoliv... ale to je jen návrh, možná to půjde jednoduššeji nějak.
> 
> Shruto:
>  * Uživatel zadá plaintext -> Vyhledávač
>  * Uživatel zadá plainext ve formátu co vymyslíme (např. [name]: Hello; [format]: video) -> Vyhledávač
>  * Uživatel nakliká -> Převedeme do našeho formátu -> Vyhledávač
> 

## Jak zobrazit
Další problémem je, že používáním gridů na zobrazení do tabulek je dost dopředu daná implementace, tedy pro každou tabulku výsledků např z materiálů by bylo potřeba vytvořit komponentu, té by se dala nějaká metoda jak získat data - jak to funguje je vidět celkem když si projdete postupně volání z nějakého prezenteru (např. MaterialPresenter.php a pak postupné volání ve funkci createComponentModifyMaterialForm() do modelu a dál a dál...).

### Gridy
Mohli bychom to naimplementovat tak, jako už několikrát pomocí gridů, ale nedokážu si představit, jak na základě toho budeme vymýšlet pak nějaké klikátko např. na přidávání masek k materiálům - asi by se dal pozměnit vzhled té tabulky aby to obsahovalo nějaké zaškrtávátko, ale nevím jak bychom to programovali.
#### Plusy:
 * Už to známe
 * Stránkování funguje i s ajaxem
 * Umíme řadit
#### Mínusy:
 * Neumíme z toho (asi) udělat klikátko na výběr věcí do formuláře...?

### Něco vlastního
Nevýhoda toho když nepoužijeme gridy je, že si budeme muset sami naimplementovat řazení a stránkování, což je zase práce navíc.
#### Plusy:
 * Nemusíme koukat na to jak to chtějí gridy, DIY
 * Můžeme si napsat vyhledávací metodu co bude vracet objekty nezávisle na gridech a výsledky si zobrazíme pak jak budem chtít
#### Mínusy:
 * Dělali jsme to jen jednou
 * Museli bychom si sami implementovat stránkování a tak - celkem dost práce navíc

Pls nápady, komentáře jak to řešit.

**Comment by shanataru** [comment]
Vyhledávání:
Mhm.. co třeba mít ten formulář s nějakými vyhledávacími parametry a ten použít i na ten plaintext vyhledávání. Třeba kdyby uživatel chtěl vyhledavat podle názvu, tak se vytáhnou ty slova co napsal a ostatní parametry by byly NULL nebo tak něco.
A pro rozšířené vyhledávání by se vytvořila stránka s klikátkama a co se nevyplní bude NULL (třeba: [keywords] zahrada, tráva; [updload_time] 8/10/17 ... [user_material] no) - u plaintext vyhledávání by bylo pak: [keywords] strom [upload_time] NULL ... [all_available_material] yes [size] NULL.

Pro zobrazení materiálů by se hodil ten grid ale třeba zatím bez klikátek (jen se základními informacemi). Pokud třeba uživatel bude chtít nahrát masku ke konkrétní textuře, tak klikne na vyhledávání textury (v tom formuláři pro nahrání masky) -> najde si materiál ale třeba u toho materiálu bude i jeho ID (pro zatím) a to ID zkopíruje do toho textového pole v tom formuláři pro upload masky :D popř. by se tam zobrazilo další pole pro další textury, pokud je maska k více texturám...
Je to lamovský ale mohlo by to fungovat.. uživatel nebude hledat podle ID ale prostě si najde to ID tý masky a překopíruje to.. ručně.. zatím. Později se to může dovylepšit .. nebo tak něco

**Comment by vojtatom** [comment]
Ok, 2 úkoly:
1) pod vyhledávacím polem bude nějaké rozšiřující klikátko - potřebujeme přesně navrhnout co tam bude (rozklikávací seznam s něčím, checklist s něčím...)
2) potřebujeme nějaký syntax pro ten plaintext (@ pro uživatele, # pro tagy a takhle) aby to šlo podle něčeho naparsovat, plus vymyslet nějaká pravidla jak to ten plaintext bude zpracovávat

**Comment by AnnaMoudra** [comment]
3. úkol
- až bude hotov syntax pro uživatelský input, tak je potřeba sepsat scénáře všech vyhledávání (nejlépe asi nějaký strom událostí ať se to co nejlíp programuje z toho) viz Wiki

**Comment by shanataru** [comment]
### Nápad č. 1: Jednoduché vyhledávání (bez dalších přídavných tlačítek nebo zaškrtávání pod polem)
Napsáním textu do vyhledávacího pole (comma separated). 

Hledání podle názvu:      keyword1, keyword2, (popř. nějaké sousloví neoddělené čárkou)
- př. voda, mořské vlny, sea.avi
- Hledání na přesnou shodu řetězce, subřetězce. Popř. jemnější hledání ignorující diakritiku nebo překlepy (vytunit se dá cokoliv)

Hledání podle autora:     @autor1 
- př. @marie
- Hledání podle shody username. **NEBO** Hledání podle zapsaného jména, příjmení (Marie Nová). Jak poté zobrazit více výsledků od různých autorů, je další problém (Marie Nová, Marie Stará).

Hledání podle tagů:        #tag1, tag2     (nebo #tag1, #tag2)
- př. #sea, #fish
- hledání TEXTUR co obsahují tyto tagy 

---
název - vyhledává se vše s tímto řetězcem
#tag - pokud uživatel zadá tag, tak vyhledávání zúží jen na textury
@autor - pokud uživatel zadá username, tak vyhledávání zúží na věci uploadnuté tímto uživatelem

### Příklady vyhledávání typ AND
**Jednotlivé části oddělené čárkou budou ve vztahu AND**:

water, #sea, waves
- Vyhoví JEN textura s názvem jako "waterywaves" A ZÁROVEŇ tagem "sea"

water, #sea, #waves
- Vyhoví textura s názvem "waterwaves" A ZÁROVEŇ tagem "sea" A ZÁROVEŇ "waves"

@user123, #sea 
- Zobrazí JEN textury už. "user123" obsahující tag "sea".
- **Nebude** hledat všechny uploadnuté věci už. "user123" a pak ještě do toho náhodný textury s tagem "sea"

@user123, #sea, water
- Vyhoví JEN textury obsahující v názvu "water" A ZÁROVEŇ s tagem "sea" uploadnuté už. "user123"

@user123, water
- Vyhoví textury, masky, binárky s názvem jako "water" uploadnuté už. "user123"

### Příklady vyhledávání typ AND-OR
**Jednotlivé části stejného typu budou ve vztahu AND-OR**:
Něco jako:
- "water" and ("#sea" or "#waves")
- "@user123" or "@user456"
- ("@user123" or "@user456") and ("water" or "sea")
- "@user123" and "#sea" and "water"

@user123
- vyhovuje všechno (textury, masky, binárky) uploadnuté pod tímto username

water, #sea, #waves (název, tag)
- Vyhovují textury s názvem jako "water123" **A** tagem "sea" NEBO "waves" NEBO oba tagy

water, waves (název, název)
- Vyhovuje cokoliv (textury, maska, binárka) s názvem jako "water01" NEBO "waves_waves" NEBO "waterwaves"

@user123, #sea, water
- Všechny textury obsahující názav jako "waterppp" s tagem "sea" uploadnuté uživatelem "user123"

water, waves, #sea, #sky
- ...

@user123, @user456
- ...

### Příklady vyhledávání typ OR
**Jednotlivé části oddělené čárkou budou ve vztahu OR**:

water, waves, #sea, #sky
- vyhovuje textura, maska, binárka s názvem jako "water", "waves_waves", "waterwaves"
- vyhovuje textura s tagem "sea" NEBO "sky"
- vyhovuje textura s názvem jako "waterwaves" s tagem "#sea"

---

### Výsledky vyhledávání a jejich zobrazení:

1. Hledání podle názvu (např. uživatel zadá "voda"):

**(A)** Výsledky vyhledávání budou zobrazené v grid, první budou textury, pak masky, pak binárky, pak zpracování. (Zobrazovat se bude třeba prvních 15 od každé skupiny)

**(B)** Na stránce budou jen materiály (textury). Výsledky opět v grid, stránkování po 15, 30, to je jedno.

**(C)** Na stránce budou textury implicitně (stránkování zase po 15, 30, to je jedno), nahoře (nebo kdekoliv) budou viditelná zaškrtávací pole pro zaškrtnutí
- Textury
- Masky
- Binárky
- Zpracování

podle toho co uživatel bude chtít hledat.

**(D)** Kromě výsledků můžeme zobrazit i předvyplněný formulář (ve formuláři už bude vyplněno slovo "voda" a budou už zaškrtnutý textury, masky, binárky,...), kde si uživatel může zvolit co přednostně vyhledává, mohlo by být možné ho (ten formulář) skrýt nebo tak něco.

2. Hledání autorových uploadnutých věcí:
Nevím, k čemu by se hledali dva autoři najednou takže zatím jenom hledání jednoho uživatele (username). Co se týče vyhledávání podle aktuálního jména (např. Jan) - zobrazení všech věcí od Janů.. nevím.

Výsledky podobné od **1. (A)** do **1. (D)**, zobrazí co daný uživatel nahrál, udělal.

3. Hledání podle tagů:
Tagy budou smíchané (to asi ničemu nevadí), výsledky zobrazení typ **1. (B)**.

**(B)** Na stránce budou jen materiály (textury). Výsledky opět v grid, stránkování po 15, 30, to je jedno.

**Comment by vojtatom** [comment]
Dotaz - budeme mít jak najít třeba materiály které obsahují tagy #modrý a zároveň #strom?

**Comment by AnnaMoudra** [comment]
Ano, or vyhledávání bude implicitní...nebo by aspoň mělo být imho

**Comment by AnnaMoudra** [comment]
A pokud myslíš materiál který má oba tyto tagy, tak za a bude vyhledán implicitně or hledanim a za B muzes zadat že tagy mají být ve vztahu and a vyhledá ti to tedy jen ty materiály co mají oba dva tagy zároveň

**Comment by vojtatom** [comment]
Je jasné že se to pomocí ORu najde vždycky, spíš mi šlo o to co napíšu do toho textového pole, jelikož máme implicitně oddělovač čárku - budeme teda něco přidávat něco jako & nebo tak? 
Taky můžem nějaké andy a ory nechat stranou a bude se vyhledávat jak píšeš jednoduše tak, že tam má být alespoň něco z těch tagů/názvů atd - spíš bych to dělal takhle

**Comment by vojtatom** [comment]
Jej už chápu - myslel jsem jestli umíme najít jenom ty kde je #modrý a #něco

**Comment by AnnaMoudra** [comment]
Ok, ještě jeden nápad. Co kdybychom se vykašlali na celý AND a pokdu to bude jen trochu logicky možné, tak bychom řadili výsledky podle četnosti výskytu? Na implementaci je to easy a z pohledu uživatele bych řekla že to taky splňuje účel.

**Comment by vojtatom** [comment]
Jen pro jistotu jestli chápu dobře příklad - mám 10 tagů které napíšu do pole, vrátí mi to 8 textur a z toho první má 6/10, druhá 5/10, třetí 3/10 atd. - takhle?

**Comment by shanataru** [comment]
Rozšířené vyhledávání bude taky podle četnosti výskytu?

**Comment by vojtatom** [comment]
Ano, něco najdeme ale stejně budeme potřebovat to nějak seřadit... plus viděl bych to tak, že to stejně bude možné pak případně řadit podle data atp, akorát že ve výchozím to budeme řadit podle četnosti.

**Comment by vojtatom** [comment]
Přidal jsem do wiki vyhledávání nějaké metody na pro ty query objekty, kdyžtak na to pls mrkněte a něco smažte/dopište, dík

**Comment by vojtatom** [comment]
První naimplementované metody QB/QO naimplementované (neděste se těch 2 joinů, jinak to bohužel nejde)...

**Comment by vojtatom** [comment]
Update - googlil jsem a DQL a Doctrine nepodporují UNION protože to jde nějak proti všemu co dělají, takže si to budem muset nějak narafičit sami. Dá se z těch query objektů dostat případně to DQLko a případně bychom ho moli pospojovat unionama a vyhodit si to z té databáza sami no a nebo si nechat ty textury vytahat z databáze a počítat si to sami... ale to by bylo takový trochu kontraproduktivní a nechutně pomalý.
Ta variant, že bychom si to DQL z topo vytahali a pospojovali by se dala podle mě klidně implementovat nad fasádou...? Idk, někdo se na to podívejte prosím

**Comment by vojtatom** [comment]
TODO - Dopsat - material->connectedToBinary() atp....
