### ISSUE TITLE
Neautorské navazování masky k materiálu

### ISSUE THREAD

**Issue by AnnaMoudra** [vojtatom/vddt#30]
Při linkování masky k materiálu se nekontroluje id uživatele. Má to tak být? I nepřihlášený uživatel může udělat změny, to by asi povoleno být nemělo.

**Comment by vojtatom** [comment]
Nepřihlášený uživatel by tohle asi neměl mít umožněno, co se ale týče přihlášeného uživatele - povolíme všem přiřazovat a nebo jen majiteli?

Problémová situace je, když cizí uživatel přiřadí masku, majitel následně označí materiál jako private a cizí uživatel tak přijde o přístup k materiálu; jaho maska ale bude pořád přiřazená k macse _což by ale nemělo vadit_, jelikož fungujeme tak, že se zobrazí a spočítají viditelné věci a neviditelné věci jako by nebyly - tím pádem aplikace nespadne ale cizí uživatel se asi naštve, že mu někdo skryl materiál k jeho masce, což my bohužel neovlivníme.

Řešením je akorát zakázat cizím uživatelům přidávat masky k cizím materiálům, což zas je (možná?) trochu na hlavu, jelikož to pak vede k tomu, že každý uživatel bude mít max svoje materiály a svoje masky... hm.

**Comment by AnnaMoudra** [comment]
Osobně jsem pro řešení naštvaného uživatele. Zakázala bych přidávání jen nepřihlášeným uživatelům a zbytek ať si to tam boří jak uznají za vhodné. Myslím, že pravděpodobnost toho, že si uživatel změní viditelnost materiálu na private je celkem malá.

**Comment by vojtatom** [comment]
Fixnuto, masky mohou momentálně navazovat pouze přihlášení uživatelé, přihlášení uživatelé mohou přidávat i oddělávat. 🦄
