### ISSUE TITLE
Změna nastavení databáze

### ISSUE THREAD

**Issue by vojtatom** [vojtatom/vddt#39]
U na localhostu sebe jsem provedl změnu v databázi, kdy user u masky, materiály, binárky a zpracování MŮŽE být nyní null (a tedy se autor vzdal autorského práva...). Bylo to potřeba kvůli kompatibilitě při mazání, prosím toto zohlednit v createscriptu pro databázi (který někde je...? prosím...?)

**Comment by shanataru** [comment]
Změnila jsem v create scriptu sloupec **user_id** u tabulek 'binaryCodes', 'mask' a 'texture' z NOT NULL na DEFAULT NULL. U tabulky 'processing' už to bylo.
