### ISSUE TITLE
Dávání věcí dokupy

### ISSUE THREAD

**Issue by vojtatom** [vojtatom/vddt#40]
Tady to vlákno je založeno z důvodu, ať je nějaký pořádek co je potřeba dodělat před odevzdáním v pondělí.

- [x] nahrát na server
- [x] zprovoznit mail
- [x] vyzkoušet upload a zpracování - nezkoušel jsem masky ale!
- [x] dopsat metodiku
- [x] dodělat titulní stránku

**Comment by vojtatom** [comment]
metodika/FAQ - https://github.com/vojtatom/vddt/wiki/FAQ-DDT by @shanataru, pak se to zkopíruje a zformátuje

**Comment by shanataru** [comment]
Jeste mam napsat poznamku ze je potreba doplnit informaci o vraceni navratove hodnoty do logu po zpracovani.

**Comment by vojtatom** [comment]
Všechno vyřízeno, ukončeno, návratovou hodnotu nakonec neřešíme, uživatel má k dispozici textový výstup binárky, tudíž má možností jak si předávat zpětně informace spoustu.
