### ISSUE TITLE
Instalace serveru

### ISSUE THREAD

**Issue by vojtatom** [vojtatom/vddt#5]
TODO's tohoto issue:

 - [x] nainstalovat lamp
 - [x] připojit disk a naformátovat
 - [x] vytvořit prázdnou databázi na serveru (nejspíše pomocí admineru, dá se to udělat tak, že se k té databázi připojí ze http://skyquality.com/www/adminer (url copypaste, neotevírá se tak jak má) tak jak to děláme doteď vlastně...)
 - [x] na disk přestěhovat to co je na gitu
 - [x] upravit apache odkud bude číst ty stránky, nejspíše pomocí symlinku na ten disk nebo tak
 - [x] propojit databázi na serveru a phpko/vddt/git/whatever
 - [x] funguje?

Podrobnosti viz níže.

---

**mysql na serveru:**
login: mysql -u root -p
password: super tajné (na vyžádání u @shanataru)

**Spouštění nějakého skriptu nad databází vddt:**
mysql -u root -p vddt < script.sql

- v **/etc/mysql/my.cnf** je pridany sql_mode v [mysqld], kvůli věcem, ale asi se to zase může smazat
- na serveru je script d130653_vddt.sql, který vytvoří prázdné tabulky (v tabulce 'processing' je pro sloupec 'date_start' hodnota timestamp místo datetime)

**Kuk na tabulky vddt databáze:**
USE vddt;
SHOW TABLES;
DESCRIBE table;

---

Budeme stěhovat server - zpočátku asi jen samotné phpko a časem někdy přestěhujeme i databázi. Zatím nemám žádné údaje atp. ale jakmile se budu mít, tak rozešlu. 

Na pomoci se stěhováním jsem se bavil už s @shanataru a prosím aby se našel ještě jeden statečný dobrovolník - hlásit se tady do komentáře.

Pak zde provedu update situace, jakmile se někdo dozvím.

**Comment by wellborntea** [comment]
o/

**Comment by vojtatom** [comment]
Dík, pořád nemám info, až bude postnu sem a pošlu do mailu.

**Comment by vojtatom** [comment]
Už se na tom dělá...

**Comment by shanataru** [comment]
Postup připojení na server přes SSH na roota, vddt.bin je privátní RSA klíč:
chmod 600 vddt.bin     (důležité!)
ssh -i vddt.bin root@147.32.233.24

Hezky se zobrazuje PHP script: http://147.32.233.24/info.php

Nainstalováno:
gcc (...)
Apache 2
MySQL
PHP 7.0

Potřeba nainstalovat:
Nette

**Comment by wellborntea** [comment]
Ten ~100GB disk rozdělen na 2 části (50GB + zbytek ~49GB) a vytvořen filesystém. Jsou namountované na /disk2 a /disk3 a (snad) připraveny k použití.

**Comment by vojtatom** [comment]
Na tom disk budou masky - textury - binárky, tak nevím jestli by nestálo za to tam hodih prostě jenom jednu to partitionu, ať se pak v budoucnu nemusíme dělat s nějakým stěhováním, až nám dojde místo. Kdyby byl ale nějaký nápad že bychom to mohli nějak rozdělit, tak sem s ním!

**Comment by wellborntea** [comment]
Ok, přehodil jsem to zatím na jednu část pod /disk2.

**Comment by vojtatom** [comment]
Vypadá to, že ten disk 2 má jen 50GB, prosím můžeš to kdyžtak opravit?

**Comment by wellborntea** [comment]
Mělo by být opraveno... předtím jsem jenom spojil partition table a navenek se to tvářilo jako funkční přes 'fdisk -l', ale 'dh -l' jsem nezkontroloval. Teď jsem to zformátoval a udělal znovu a vypadá to už správně.

**Comment by vojtatom** [comment]
Supr dík, vypadá to v pohodě! Nahoře v prvním příspěvku je kdyžtak todo list, aby se vědělo co dál.

**Comment by vojtatom** [comment]
Přemístil jsem tam obsah gitu, neche se to načíst, ale už je to tam.

**Comment by vojtatom** [comment]
pro to, aby vám git ftp fungoval pro přestěhovaný git, stačí v adresáři s naklonovaným vddt spustit:
```bash
git config git-ftp.url sftp://147.32.233.24/../disk2/vddt/
git config git-ftp.user root
#upravit ~/.ssh/vddt na jméno a lokaci ssh klíče u vás
git config git-ftp.key ~/.ssh/vddt
```
alespoň git upload funguje

**Comment by vojtatom** [comment]
bude potřeba zprovoznit spojení s databází z vddt na serveru - je ve složce /disk2/vddt, mělo by stačit nastavit config v app/config - prosím někdo jestli se k tomu dostane, heslo k databázi má @shanataru
