### ISSUE TITLE
Složka .idea 

### ISSUE THREAD

**Issue by vojtatom** [vojtatom/vddt#7]
Prosím najděte někdo co ze složky .idea se dá hodit do gitignoru, ať se to sem pořád necommituje všechno.

**Comment by vojtatom** [comment]
https://www.gitignore.io - mohlo by se hodit

**Comment by shanataru** [comment]
To je z IDEčka? Já bych tam hodila všechno. :D

**Comment by vojtatom** [comment]
Myslím že z PHPstorm nebo tak, stačí asi hodit do oho linku výše PHPstorm a když už budem něco dávat do ignoru, tak tam napište i věci z windows, linux a macos.

**Comment by shanataru** [comment]
Uhm.. uz by to melo byt snad vsechno z .idea

**Comment by vojtatom** [comment]
Definitivně upraveno a vymazáno z histore commitů v commitu 972f20407cf8f1cfebaef61dabe84c3c5276a294... Toto celé se nikdy nestalo.

**Comment by vojtatom** [comment]
Copy - paste ze slacku, pokud tam nejste tak mrkněte do mailu, mohlo by se hodit;

Ad nefungující ftp - zdá se že je problém v tom, že když děláte commit, tak nejsou pomocí add přidané všechny změny ve všech změněných souborech - nejspíš to má taky něco do činění s tou složkou .idea. Pokud jsou problémy s add, nepomůže individuální přidávání po souborech, je potřeba použít “git add .” - tohle ideálně používat pořád a pak se zdá že by to mělo být ok. Krom toho jsem nic zatím neopravoval, dokud funguje sync na git, tak je to v pohodě, git ftp počká holt...
