### ISSUE TITLE
Ošetření operace nahrávání nevalidního souboru

### ISSUE THREAD

**Issue by shanataru** [vojtatom/vddt#9]
Ošetření výjimek při nahrání materiálu, binárky, masky.

**Comment by vojtatom** [comment]
V 9848f5b150829c7ef42d5c180cb627cf854e0196 byl přidán FileManager který  řeší toto issue. Je potřeba otestovat a naimplementovat fallback pro případ nevalidního souboru.

**Comment by vojtatom** [comment]
Vyřešeno v 59061113820bde32d1b7018eb8d0efa6d7b57534.
